main: tfmc.justin.SurgeryPlugin
version: ${project.version}
name: surgery
author: Justin
api-version: '1.21.10'
depend: [TLibs]

commands:
  surgery:
    description: Opens the surgery menu
    usage: /surgery <player_name>
    permission: surgery.use

permissions:
  surgery.use:
    description: Allows performing surgery on another player
    default: true