main: net.tfminecraft.surgery.SurgeryPlugin
version: ${project.version}
name: surgery
author: Justin
api-version: '1.21.10'
depend: [TLibs, RPCharacters]

commands:
  surgery:
    description: Offer surgery to a patient, or accept or deny an offer
    usage: /surgery <player> | accept | deny
